name: Update OpenAPI Spec

on:
  pull_request:
    paths:
      - 'swagger.json'

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  STAINLESS_ORG: cjavalphavantage
  STAINLESS_PROJECT: cjav-json-scratch
  OAS_PATH: ./openapi.json

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Convert Swagger to OpenAPI
        uses: stainless-api/upload-openapi-spec-action/prepare/swagger@v1.10.0
        with:
          input_path: ./swagger.json
          output_path: ${{ env.OAS_PATH }}
          commit: true

  preview:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: Capture new head SHA
        id: sha
        run: |
          echo "head_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.sha.outputs.head_sha }}
          fetch-depth: 0

      - uses: stainless-api/upload-openapi-spec-action/preview@v1
        with:
          head_sha: ${{ steps.sha.outputs.head_sha }}
          org: ${{ env.STAINLESS_ORG }}
          project: ${{ env.STAINLESS_PROJECT }}
          oas_path: ${{ env.OAS_PATH }}