name: Update OpenAPI Spec

on:
  pull_request:
    paths:
      - 'swagger.json'

permissions:
  contents: write
  pull-requests: write

env:
  STAINLESS_ORG: cjavalphavantage
  STAINLESS_PROJECT: cjav-json-scratch
  OAS_PATH: ./openapi.json

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stainless-api/upload-openapi-spec-action/prepare/swagger@v1.10.0
        with:
          input_path: ./swagger.json
          output_path: ${{ env.OAS_PATH }}
          commit: true

      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 2

      - name: Run preview builds
        uses: stainless-api/upload-openapi-spec-action/preview@v1
        with:
          org: ${{ env.STAINLESS_ORG }}
          project: ${{ env.STAINLESS_PROJECT }}
          oas_path: ${{ env.OAS_PATH }}