name: Update OpenAPI Spec

on:
  pull_request:
    paths:
      - 'swagger.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
      - uses: cjavdev/upload-openapi-spec-action/prepare/swagger@v1
        with:
          input_path: ./swagger.json
          output_path: ./openapi.json
          commit: true
